### ISSUE TITLE
Remove deprecated HCL actions?

### ISSUE THREAD

**Issue by nathany** [sdras/awesome-actions#158]
I was excited to come across these awesome actions, but it appears that some of the links use the now deprecated HCL syntax-based actions.

Would it make sense to remove or move the actions that use HCL to give emphasize ones that use the current YAML syntax?

Related: https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax

**Comment by gep13** [comment]
>@nathany said...
some of the links use the now deprecated HCL syntax-based actions.

As per the link that you posted, HCL syntax isn't quite at the deprecated stage yet, but I do agree that we might want to separate, or at least highlight, that a particular action uses a particular format.

Is this something that you would like to take a stab at?

**Comment by clarkbw** [comment]
> Support for the HCL syntax in GitHub Actions will be deprecated on September 30, 2019.

The Actions should continue to work however the workflow setups won’t and should be updated.

**Comment by gep13** [comment]
@clarkbw that is good to know!  Thank you for confirming that.

@nathany based on this knowledge, I don't see any immediate need to alter the list as it currently stands.  Do you?

**Comment by sdras** [comment]
Yeah, I think the list should make mention of this. I'll work on this unless someone else wants to take it.

**Comment by gep13** [comment]
@sdras that would be great if you could, thank you!

While you are here, can I ask if you saw this: https://github.com/sdras/awesome-actions/issues/95  Thanks!

**Comment by DannyBen** [comment]
For what its worth, I think that even though the HCL syntax is not yet deprecated, it should be considered at least outdated. It had a short shelf-life, and sifting through the list just to find out many things are not relevant, is just adding to the confusion.

I believe the approach to updating this repo should be to separate the HCL to the bottom of the list, or to a separate document, and keep the list clean, focusing exclusively on the new syntax.

**Comment by gep13** [comment]
@DannyBen did you want to take a stab at doing this?

**Comment by DannyBen** [comment]
I thought @sdras was on the case, no?

**Comment by gep13** [comment]
That was back in August last year, and since then, the `help wanted` label has been added, so I am going to say that it is open for contributions.

**Comment by DannyBen** [comment]
Ok - I promise to take a look and see if I have the time for it. There are tons of links there, each needs to be carefully reviewed and migrated. No promises, but I might find the time during the weekend.

Do we prefer adding a "(HCL)" (or other) marker neear HCL only items, or do we prefer a completely separate list? The former will probably be easier, since the latter might create weird lists (since they will lose many if not all items).
