### ISSUE TITLE
Request: Add about GitHub Actions official status badge

### ISSUE THREAD

**Issue by peaceiris** [sdras/awesome-actions#161]
cf. [GitHub Actions official status badges : github](https://www.reddit.com/r/github/comments/csehoc/github_actions_official_status_badges/)

GitHub Actions provides official CI/CD status badges.

[![](https://github.com/actions/toolkit/workflows/Main%20workflow/badge.svg)](https://github.com/actions/toolkit)

```md
example:
[![](https://github.com/actions/toolkit/workflows/Main%20workflow/badge.svg)](https://github.com/actions/toolkit)

URL format:
https://github.com/{github_id}/{repository}/workflows/{workflow_name}/badge.svg
```

The official document about the badge has not been written yet.

**Comment by gep13** [comment]
@peaceiris can you please clarify what you are suggesting here?  Are you suggesting adding a status badge for the workflow that is being used in this repository?  Or something else?

**Comment by peaceiris** [comment]
I suggest the following:
- Add a status badge of this repo's workflow.
- Add information about CI status badges to `README.md`

**Comment by gep13** [comment]
@peaceiris sounds good to me!  Would you be in a position to submit a PR for that?

**Comment by peaceiris** [comment]
> Would you be in a position to submit a PR for that?

Yes, I will submit a PR.

I think that the status badge of this repo should be added at the top of README or next to the AWESOME icon. And, information about the status badge should be added to the [Official Resources](https://github.com/sdras/awesome-actions#official-resources).

How about you?

**Comment by gep13** [comment]
Badge at the top makes sense to me, and official resources sounds good to me.

**Comment by peaceiris** [comment]
I created the Pull Request #162

**Comment by gep13** [comment]
@peaceiris thanks again for this!
