### ISSUE TITLE
New repository: GitHub Actions Branding Cheat Sheet

### ISSUE THREAD

**Issue by peaceiris** [sdras/awesome-actions#206]
I found the following new project. Where should it belong to?

- [haya14busa/github-action-brandings: GitHub Actions Branding Cheat Sheet](https://github.com/haya14busa/github-action-brandings)

**Comment by gep13** [comment]
@peaceiris hmm, I am not sure 😄 Perhaps it deserves its own section, but I am struggling to think what would be best to name it!

**Comment by peaceiris** [comment]
How about creating a new section "cheat sheet"?

**Comment by gep13** [comment]
@peaceiris I would have no objections to that.

**Comment by peaceiris** [comment]
OK. I created my Pull Request #221
