### ISSUE TITLE
Broken link to actions tab

### ISSUE THREAD

**Issue by gep13** [sdras/awesome-actions#232]
I have just remove the link used by the actions shield on the readme.  You can see the commits here:

https://github.com/sdras/awesome-actions/commit/f898300b4beebd2535b0ad5fcf2f68e62f8f2353
https://github.com/sdras/awesome-actions/commit/ccd2216ce0b8a9c23032bef4a0bc58c4450aa58a

For some reason, the URL:

https://github.com/sdras/awesome-actions/actions?workflow=Lint+Awesome+List

and

https://github.com/sdras/awesome-actions/actions

are now causing a 404 to be detected by the lint action.

https://github.com/sdras/awesome-actions/commit/f898300b4beebd2535b0ad5fcf2f68e62f8f2353/checks?check_suite_id=268739013#step:4:8
https://github.com/sdras/awesome-actions/commit/0c71d83855e542e37018a589e3c57b39bebae367/checks?check_suite_id=268736928#step:4:8

No idea what is going on here.  Today I have added another action to the repository which could be causing a problem?

@peaceiris any ideas?

**Comment by peaceiris** [comment]
I got it. That is simple. We need to login to GitHub to access the actions tab.

**Comment by gep13** [comment]
@peaceiris thanks for looking into this, I appreciate it!

**Comment by SuperKogito** [comment]
I think you can avoid broken links using an action I recently wrote [URLs-checker](https://github.com/marketplace/actions/urls-checker) .This action will check and report broken links. Alternatively, you can use [URL Cheker](https://github.com/marketplace/actions/url-checker).

**Comment by peaceiris** [comment]
This issue will be fixed by #270.

**Comment by gep13** [comment]
>@SuperKogito said...
I think you can avoid broken links using an action I recently wrote URLs-checker .This action will check and report broken links. Alternatively, you can use URL Cheker.

Thank you for your suggestion.  The awesome lint action that is currently being used is already identifying broken links, that is how this issue came up in the first place.  @peaceiris has worked around this problem though, so we should be in a position to move forward.
