### ISSUE TITLE
Use linter ignore option for actions/github

### ISSUE THREAD

**Issue by peaceiris** [sdras/awesome-actions#246]
https://github.com/sdras/awesome-actions/blob/b96b69f01687c1752da311fb98cde84aadbb3ac5/README.md#L67

By https://github.com/sindresorhus/awesome-lint/pull/78, we will be able to use the lint disable statement to ignore `Text "github" should be written as "GitHub"  remark-lint:awesome/spell-check`

```diff
- `actions/github`
+ actions/github
```

```md
<!--lint disable awesome-list-item-->
- [actions/github](https://github.com/actions/github) - Wraps actions-toolkit into an Action for common GitHub automations.
<!--lint enable awesome-list-item-->
```

**Comment by gep13** [comment]
@peaceiris was this created just for reference, or is there anything else that needs to be done here?

**Comment by peaceiris** [comment]
This issue is our task to unify the readme format.

![github](https://user-images.githubusercontent.com/30958501/68568665-938ca280-049f-11ea-9465-808c80e4affd.jpg)

**Comment by gep13** [comment]
@peaceiris gotcha, now I see what you mean!  👍
