### ISSUE TITLE
Have two sections for Actions and Workflows

### ISSUE THREAD

**Issue by lannonbr** [sdras/awesome-actions#26]
I think it could be a good decision to possibly separate the "Community Resources" into an "actions" and "workflows" as some people may share solo-actions while others may share workflows that use a large series of actions.

What are everyone's thoughts on this?

**Comment by sdras** [comment]
I think it's a good proposal but I don't think we should head in that direction because it doesn't leave a lot of room for projects to scale. Besides, every action has a workflow even if it's single, so people could easily confused here. I'm open to other ways of splitting things up though.
