### ISSUE TITLE
Break up linting and testing into two separate groups, possibly a third - monitoring

### ISSUE THREAD

**Issue by jessicalostinspace** [sdras/awesome-actions#303]
Linting and Testing should be two separate groups with possible sub groups. For example: under linting, each language could be split into subgroups or a groupd like "reviewdog" which has several entries not grouped together under the linting category. Monitoring could also be separated out to its own group (ie. scanning code quality, code coverage, etc). "Scan git commits for secrets with gitleaks" and "Scan for secrets in your source code" should also be moved to "Security" group.

**Comment by jessicalostinspace** [comment]
Monitoring could also be separated out to its own group (ie. scanning code quality, monitoring, etc)

**Comment by jessicalostinspace** [comment]
"Scan git commits for secrets with gitleaks" should also be moved to "Security" group

**Comment by gep13** [comment]
@jessicalostinspace this makes a lot of sense to me.  Would you be in a position to send in a PR to make these changes?
