### ISSUE TITLE
awesome-lint no-dead-urls error

### ISSUE THREAD

**Issue by ssowonny** [sdras/awesome-actions#363]
It seems that Github links return 429 (Too many requests) HTTP error since [awesome-lint](https://github.com/sindresorhus/awesome-lint#readme) sends too many requests to Github concurrently. It would be better to suppress the `no-dead-urls` lint error or find a way to setup delays between the requests.

**Comment by jessicalostinspace** [comment]
I've put in a temporary fix to disable the no-dead-urls check until a more robust solution is implemented in the base linter. We should leave this issue up until a fix is put into place so the temporary fix can be removed: https://github.com/sdras/awesome-actions/pull/377.

**Comment by ssowonny** [comment]
@jessicalostinspace Awesome, thanks :+1:

**Comment by sdras** [comment]
Just fixed this :) Thanks!
