### ISSUE TITLE
Add to Security - GitHub Actions secrets manager CLI

### ISSUE THREAD

**Issue by unfor19** [sdras/awesome-actions#398]
# githubsecrets

Official page - https://github.com/unfor19/githubsecrets

### GIF Demo
![GIF Demo](https://camo.githubusercontent.com/07c8359e56db70ff90f3111bce474a4530775c88/68747470733a2f2f676974687562736563726574732e73332d65752d776573742d312e616d617a6f6e6177732e636f6d2f676974687562736563726574732d64656d6f2e676966)

Install with pip
```bash
$ pip install githubsecrets
...
$ ghs --help
...
```

Or use with Docker (you must supply all arguments, prompts are not available in Docker mode)

macOS and Linux
```bash
$ docker run -v $HOME:/root unfor19/githubsecrets --help
Usage: ghs [OPTIONS] COMMAND [ARGS]...
```

Windows
```bash
$ docker run --rm -v c:/Temp:/root unfor19/githubsecrets --help
Usage: ghs [OPTIONS] COMMAND [ARGS]...
```

**Comment by jessicalostinspace** [comment]
Hi @unfor19 , this should be opened up as a PR, not an issue.

**Comment by unfor19** [comment]
@jessicalostinspace sorry for that, will do
