### ISSUE TITLE
Request: Action that provides commit suggestions on PRs based on linting

### ISSUE THREAD

**Issue by polarathene** [sdras/awesome-actions#461]
For linters like [textlint](https://textlint.github.io/) where you may not want changes run prior to PR submission(eg manually invoked or pre-commit hook), a Github Action that can run the linter and for any `--fix` supported suggestions have the `suggestion` codefence syntax share those for the author to apply conditionally or discuss would be great.

Additionally for linters such as eslint when a change doesn't have `--fix` support, similar report could be shared in the PR, just without actionable commit suggestion UI.

**Comment by sdras** [comment]
This is not a place to request actions to be created, it's an aggregate of actions that have already been created. Closing as it's out of scope for the project.
