### ISSUE TITLE
Pull Request Stuck Notifier link is dead

### ISSUE THREAD

**Issue by Molkree** [sdras/awesome-actions#463]
[Pull Request Stuck Notifier](https://github.com/loomble/pull-request-stuck-notifier-action) is no longer available. I guess the copy is [here](https://github.com/jrylan/github-action-stuck-pr-notifier), as it is the person who proposed to add it to the list in the first place #267.

**Comment by sdras** [comment]
We're open to a PR to update, otherwise we will handle it ourselves :)
