### ISSUE TITLE
Fix awesome lint

### ISSUE THREAD

**Issue by negebauer** [sdras/awesome-actions#465]
A lot of prs are falling due to https://github.com/actions being duplicated in the README

https://github.com/sdras/awesome-actions/blob/fa3e308e507da613d3bec2ed3380d632852d965e/README.md#L9

https://github.com/sdras/awesome-actions/blob/fa3e308e507da613d3bec2ed3380d632852d965e/README.md#L42

**Comment by sdras** [comment]
I'll look into this, thanks

**Comment by sdras** [comment]
This error should be fixed now.

**Comment by negebauer** [comment]
Yes it is, nice
![image](https://user-images.githubusercontent.com/11860880/91500381-69229f00-e891-11ea-92a0-ed897c624dbc.png)
