### ISSUE TITLE
Help manage the repo

### ISSUE THREAD

**Issue by andrewthetechie** [sdras/awesome-actions#604]
Hi @sdras, are you still interested in maintaining this list? Would you be ok with a fork and someone else updating the list? 

Another possible option: Would you be interested in adding some folks to manage this repo? I'd volunteer to help out with reviewing PRs and getting more actions added to the list.

**Comment by GeauxWeisbeck4** [comment]
I would like to help out if at all possible as well. This is a really solid stack.

**Comment by sdras** [comment]
Hey all, I'd happy to have the help. My job is taking up a ton of my time these days. I'll add you to the repo. Please read through the [contributing](https://github.com/sdras/awesome-actions/blob/main/contributing.md) guide. Thank you!

**Comment by cicirello** [comment]
@sdras I'd be happy to assist maintaining this as well. It's a great resource for finding quality GitHub Actions.

**Comment by alagos** [comment]
@sdras happy to help here as well. There's a bunch of PRs that need some attention

**Comment by inverse** [comment]
First up - awesome to see a curated place of awesome actions and resources :) 

Are any other folks contributors to this repo as it feels like it's not had a merge for over 1 year with almost 100 PRs piled up?
