### ISSUE TITLE
Project Icon should be png or svg

### ISSUE THREAD

**Issue by gep13** [sdras/awesome-actions#95]
As noted in this comment:

https://github.com/sindresorhus/awesome/pull/1432#issuecomment-446765509

The project icon should be either a PNG or an SVG.

@sdras do you have the original source files that was used to generate this icon?  If so, can we get it updated?

**Comment by gep13** [comment]
@sdras I just wanted to touch base on this again.  Is this something that you have?  Thanks!

**Comment by gep13** [comment]
@adilio fyi...

**Comment by gep13** [comment]
https://image.ibb.co/cZ1q5f/awesome-actions.jpg

**Comment by peaceiris** [comment]
The GitHub Actions icon seems to be changed.

- https://github.com/actions

![actions](https://user-images.githubusercontent.com/30958501/68524412-f2201800-0309-11ea-9cb0-ad7f8f760218.png)

**Comment by adilio** [comment]
Here is my attempt at a similar scaleable version:

PNG: https://www.dropbox.com/s/ticaekyl4ov3t5u/awesome-icon.png?dl=0
SVG: https://www.dropbox.com/s/69l7qsf4xflacma/awesome-icon.svg?dl=0

![awesome-icon](https://user-images.githubusercontent.com/21287462/68552744-55c04900-03cf-11ea-8f23-017679ae214d.png)

**Comment by gep13** [comment]
@adilio thank you very much for taking the time to do this.  I am going to try to get this tidied up over the next couple days, so that I can get this list added into the official main list of awesome lists 😄

**Comment by sdras** [comment]
fixed

**Comment by gep13** [comment]
@sdras thank you for fixing this up, appreciate it!

**Comment by sdras** [comment]
my pleasure @gep13! I also re-submitted the awesome PR :)

**Comment by gep13** [comment]
>@sdras said...
I also re-submitted the awesome PR :)

I spotted that 😄 https://github.com/sindresorhus/awesome/pull/1671

Hopefully it will be accepted this time.
