### ISSUE TITLE
Checks not working on all PR's

### ISSUE THREAD

**Issue by gep13** [sdras/awesome-actions#98]
For example, there are no checks on this PR:

https://github.com/sdras/awesome-actions/pull/97/checks

@sdras I am not able to see the settings of this repository, are you able to confirm how the settings are set up in this area?  It would be good to have the awesome-lint action that @max added to this repository working on all PR's.

**Comment by xt0rted** [comment]
I think the workflow needs to be changed from `push` to `pull_request`. Or a second workflow added for `pull_request`.

**Comment by gep13** [comment]
@xt0rted I think you could be right!  Thanks for posting here.

Would you mind creating a new PR on this repo to test this out?  I have switched the workflow to trigger on `pull_request`.

**Comment by xt0rted** [comment]
#99 I'm not seeing any checks yet though 😕

**Comment by gep13** [comment]
@xt0rted I am starting to think that there is a setting that is required to make this work, but not sure what...

I will reach out to someone who might be able to help.

**Comment by gep13** [comment]
@xt0rted The checks also showed up correctly on a PR that I raised here:

https://github.com/sdras/awesome-actions/pull/96

This was before switching to `pull_request` as well.

**Comment by xt0rted** [comment]
I set up a new workflow yesterday and had everything running on `pull_request` but what I found was even updating a PR's labels triggered the actions to run. I think you were right having this run on `push` because when I changed it over to `push` it continued running for commits but not for other changes (labels, projects, etc.).

**Comment by gep13** [comment]
@xt0rted while you are here... was this on a private repo you were testing?  I seem to remember that there is a limitation on what works on a public repo while in the GitHub Actions beta.

**Comment by gep13** [comment]
@xt0rted for now, I have switched back to the push event.

**Comment by xt0rted** [comment]
It was a private repo where they were running after changing the labels of a PR. It makes sense after looking at the api more, the `pull_request` event is fired for anything related to a PR.

According to https://developer.github.com/actions/creating-workflows/workflow-configuration-options/#pull-request-events-for-forked-repositories
>If you intend to use the `pull_request` event to trigger CI tests, it's recommended to listen to the `push` event.

Also found https://developer.github.com/actions/changes/2018-12-18-limited-public-actions/
>GitHub Actions can now be triggered on push events in public repositories _by repository owners._

I'm not sure if this update changed any of that though https://developer.github.com/actions/changes/2019-01-29-public-actions-update/

**Comment by gep13** [comment]
Hmm, very strange then. I will follow up directly with GitHub support, to see if I can get an answer.

**Comment by gep13** [comment]
@xt0rted I have heard back from GitHub support on this, seems like this is known issue 😢 

> I'm afraid check runs for Actions do not currently show on Pull Requests when it's between a parent and a fork. This is something the team would like to improve upon in the future.

Guess we will simply have to wait and see if/when this ships.  This is a real shame.  Seems like this is an obvious thing that should/needs to be supported.

**Comment by gep13** [comment]
This does explain why the checks appeared on the PR that I created, as this from a PR from this repository, and not a fork.

**Comment by aequasi** [comment]
Oof. That is quite the deal breaker... What a bummer

**Comment by gep13** [comment]
@aequasi I am actually curious if this now “just works” would you be willing to test this out by sending a PR into this repo?

**Comment by max** [comment]
@gep13 This will not “just work”. We’ve recently launched an updated version of GitHub Actions that does enable this workflow. I can flag this repository in but it requires updating the configuration file – we have changed the format. I’m happy to send you all a PR...

**Comment by gep13** [comment]
@max oh wow! If you could do both of those things, that would be great, thank you!

**Comment by aequasi** [comment]
Is there any documentation on that?

**Comment by max** [comment]
https://help.github.com/en/articles/about-github-actions

**Comment by gep13** [comment]
Very happy to say that this is now up and running!  Huge thanks to @max for his help on this!
